---
name: Linting and Formatting
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Implement linting and formatting checks (TODO)
        run: |-
          echo "TODO: Implement linting and formatting checks"
